# Generated by Django 3.1.6 on 2021-02-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210205_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'OTHER')], default=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
