# Generated by Django 3.1.6 on 2021-02-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('users', '0003_auto_20210211_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.ManyToManyField(to='hospital.Disease'),
        ),
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.room'),
            preserve_default=False,
        ),
    ]
